baseURL = "https://example.com"
languageCode = "en"
defaultContentLanguage = "en"
title = "Hill Media"
theme = "raditian"

paginate = 12
enableEmoji = true
enableRobotsTXT = true
[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

# [menu]
#   [[menu.main]]
#     name = "Home"
#     url = "/"
#     weight = 1

[params]
    since = 2022
    author = "Hill Media"               # Author's name
    subtitle = "A new type of media"       # Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "" # post or other
    dateFormatToUse = "" # set date format, default "2 January 2006"

    avatar = "/images/social.jpg" #comment it to use gravatar
    socialShare = true

    description = "Hill Media A NEW TYPE OF MEDIA" # site description
    keywords = "" # site keywords
    disableThemeToggle = true
     defaultTheme = "light"

# [params.gravatar]
    #email = "example@gmail.com"   #uncomment and insert your email address to use gravatar


# [params.social]
    # GitHub = "xxxx"
    # Linkedin = "xxxx"
    # Twitter = "xxxx"
    #Instagram = "xxxx"
    #Email   = "xxxx"
    # Facebook = "xxxx"
    #Telegram = "xxxx"
    #Medium = "xxxx"
    #Gitlab = "xxxx"
    #Youtubelegacy = "xxxx"
    #Youtubecustom = "xxxx"
    #Youtubechannel = "xxxx"
    #Tumblr ="xxxx"
    #Quora = "xxxx"
    #Keybase = "xxxx"
    #Pinterest = "xxxx"
    #Reddit = "xxxx"
    #Codepen = "xxxx"
    #Bitbucket = "xxxx"
    #Stackoverflow = "xxxxx"
    #Weibo = "xxxx"
    #Odnoklassniki = "xxxx"
    #VKontakte = "xxxx"
    #Flickr = "xxxx"
    #Xing = "xxxx"
    #Snapchat = "xxxx"
    #Soundcloud = "xxxx"
    #Spotify = "xxxx"
    #Bandcamp = "xxxx"
    #Paypal = "xxxx"
    #Fivehundredpx = "xxxx"
    #Mix = "xxxx"
    #Goodreads = "xxxx"
    #Lastfm = "xxxx"
    #Foursquare = "xxxx"
    #Hackernews = "xxxx"
    #Kickstarter = "xxxx"
    #Patreon = "xxxx"
    #Steam = "xxxx"
    #Twitch = "xxxx"
    #Strava = "xxxx"
    #Skype = "xxxx"
    #Whatsapp = "xxxx"
    #Zhihu = "xxxx"
    #Douban = "xxxx"
    #Angellist = "xxxx"
    #Slidershare = "xxxx"
    #Jsfiddle = "xxxx"
    #Deviantart = "xxxx"
    #Behance = "xxxx"
    #Dribble = "xxxx"
    #Wordpress = "xxxx"
    #Vine = "xxxx"
    #Googlescholar = "xxxx"
    #Researchgate = "xxxx"
    #Mastodon = "xxxx"
    #Thingiverse = "xxxx"

[params.share]
Twitter = true
Facebook = true
#Reddit = true
# Linkedin = true
#Pinterest = true
#HackerNews = true
#Mix = true
#Tumblr = true
#VKontakte = true
#Douban = true
#Weibo = true

# Used only for Seo schema
# copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."

[author]
  name = "Hill Media"

  [params.publisher]
    name = "Fastbyte01"

    [params.publisher.logo]
      url = "logo.png"
      width = 127
      height = 40

  [params.logo]
    url = "logo.png"
    width = 127
    height = 40

  [params.image]
    url = "cover.png"
    width = 800
    height = 600

[params.gitalk]
owner = ""       # Your GitHub ID
repo = ""        # The repo to store comments
clientId = ""    # Your client ID
clientSecret = "" # Your client secret

[params.valine]
  enable = false
  language = 'en'
  appId = 'your appId'
  appKey = 'your appKey'
  notify = false  # mail notifier , https://github.com/xCss/Valine/wiki
  verify = false # Verification code
  avatar = 'mm'
  placeholder = 'your comments ...'
  visitor = true

[params.utterances]       # https://utteranc.es/
    owner = ""              # Your GitHub ID
    repo = ""               # The repo to store comments

[params.gitment]          # Gitment is a comment system based on GitHub issues. see https://github.com/imsun/gitment
    owner = ""              # Your GitHub ID
    repo = ""               # The repo to store comments
    clientId = ""           # Your client ID
    clientSecret = ""       # Your client secret
